### ISSUE TITLE
Add a check if the `rust` is installed

### ISSUE THREAD

**Issue by tesla33io** [tesla33io/better-tree#1]
Before installing the program, add a check to see if the `rust` is installed on the system.

**Comment by harshRn** [comment]
Hi @tesla33io 
Can you specify the installation medium ? Would I be correct in assuming that in case of a "cargo install" , Rust, indeed, is installed ?

**Comment by tesla33io** [comment]
Hi @harshRn!

I'm pleasantly surprised to see attention on this issue! 😅 
When you mention the installation medium for `rust`, are you referring to the [installation guide](https://www.rust-lang.org/tools/install)? 

To check if `rust` is installed, you can run any `rust`-related command. If you receive `'[bash|zsh]: cargo: command not found'` (or something similar), it indicates that Rust isn't installed. Conversely, if you don't encounter this error, it means Rust is indeed installed.

Does this address your question?

P.S.: Essentially, the aim of this issue is to incorporate a check for `rust` installation before executing `cargo build --release` in the Makefile.

**Comment by harshRn** [comment]
Hi @tesla33io,
Thanks for getting back to me. It does kind of clarify things. If somebody wants to install the app using 'cargo install' this check would not need to be performed. In case somebody decides to install it something like homebrew, apt(provided you make it available), it will indeed need to make the check. I will take this up if you think I understand it correctly and see what I can come up with. Lmk. Thanks!

**Comment by tesla33io** [comment]
Hey @harshRn, appreciate your help!
You have a correct understanding.
However I don't plan to add this project to any package managers until some useful and unique functionality will be implemented. 
Currently it could be installed only from this repository following the installation guide provided in [README](https://github.com/tesla33io/better-tree?tab=readme-ov-file#installation).
So, for now check for installed `rust` needed only in Makefile.
Let me know if you have any questions!

**Comment by harshRn** [comment]
Addressed here : https://github.com/tesla33io/better-tree/pull/2
